# Generated by Django 5.0 on 2025-09-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_applicant_first_name_alter_applicant_last_name_and_more'),
        ('jobs', '0004_remove_application_unique_application_per_listing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='applicant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.applicant'),
        ),
        migrations.AddConstraint(
            model_name='application',
            constraint=models.UniqueConstraint(fields=('applicant', 'listing'), name='unique_application_per_listing'),
        ),
    ]
