# Generated by Django 5.0 on 2025-10-20 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_application_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('applied', 'Applied'), ('review', 'Under Review'), ('interview', 'Interview'), ('offer', 'Offer'), ('closed', 'Closed')], default='applied', max_length=20),
        ),
    ]
