# Generated by Django 5.0 on 2025-10-20 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_application_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='stage',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Interview', 'Interview'), ('Offer', 'Offer'), ('Closed', 'Closed')], default='Applied', max_length=20),
        ),
    ]
