# Generated by Django 5.0 on 2025-10-21 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0008_alter_application_stage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='stage',
            new_name='status',
        ),
    ]
