# Generated by Django 5.2.6 on 2025-11-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0009_rename_stage_application_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='country',
            field=models.CharField(default='USA', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='post_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
