# Generated by Django 5.2.6 on 2025-11-06 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_jobposting_city_jobposting_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='street_address',
            field=models.CharField(default='', help_text='Street address', max_length=200),
        ),
    ]
