# Generated by Django 5.2.5 on 2025-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_alter_jobposting_street_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobposting',
            name='street_address',
            field=models.CharField(help_text='Street address', max_length=200),
        ),
    ]
