# Generated by Django 5.0 on 2025-11-16 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_jobposting_location_lat_jobposting_location_lon_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='visibility',
            field=models.CharField(default='public', help_text='Job visibility', max_length=10),
        ),
    ]
