# Generated by Django 5.2.5 on 2025-09-23 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_recruiter_location_alter_recruiter_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicant',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='applicant',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='recruiter',
            name='last_name',
        ),
    ]
