# Generated by Django 5.2.5 on 2025-09-23 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_applicant_first_name_applicant_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='applicant',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='first_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='recruiter',
            name='last_name',
            field=models.CharField(max_length=30),
        ),
    ]
