# Generated by Django 5.0 on 2025-09-24 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_applicant_first_name_alter_applicant_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='projects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
