# Generated by Django 5.0 on 2025-10-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('country', models.CharField(max_length=100)),
                ('state_province', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(max_length=100)),
                ('is_remote', models.BooleanField(default=False)),
                ('is_major_city', models.BooleanField(default=False)),
                ('population', models.IntegerField(blank=True, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_major_city', '-population', 'name'],
                'indexes': [models.Index(fields=['name'], name='accounts_lo_name_02cb9f_idx'), models.Index(fields=['country', 'state_province'], name='accounts_lo_country_a5e57f_idx'), models.Index(fields=['is_remote'], name='accounts_lo_is_remo_71d80f_idx'), models.Index(fields=['is_major_city'], name='accounts_lo_is_majo_b1116f_idx')],
            },
        ),
    ]
