# Generated by Django 5.0 on 2025-10-02 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='availability',
            field=models.CharField(choices=[('available', 'Available Now'), ('open-to-work', 'Open to Work'), ('not-looking', 'Not Looking')], default='open-to-work', help_text='Current job search status', max_length=20),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
