# Generated by Django 5.0 on 2025-10-21 15:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_applicant_availability_applicant_location_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicantPrivacySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_skills', models.BooleanField(default=True, help_text='Show skills to recruiters')),
                ('show_education', models.BooleanField(default=True, help_text='Show education to recruiters')),
                ('show_experience', models.BooleanField(default=True, help_text='Show experience to recruiters')),
                ('show_projects', models.BooleanField(default=True, help_text='Show projects to recruiters')),
                ('show_links', models.BooleanField(default=True, help_text='Show links to recruiters')),
                ('show_phone', models.BooleanField(default=False, help_text='Show phone number to recruiters')),
                ('show_location', models.BooleanField(default=True, help_text='Show location to recruiters')),
                ('show_availability', models.BooleanField(default=True, help_text='Show availability status to recruiters')),
                ('allow_messages', models.BooleanField(default=True, help_text='Allow recruiters to message you')),
                ('allow_email_contact', models.BooleanField(default=True, help_text='Allow recruiters to email you')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('applicant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to='accounts.applicant')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient'], name='accounts_me_sender__c8fd82_idx'), models.Index(fields=['recipient', 'is_read'], name='accounts_me_recipie_a9e6c4_idx')],
            },
        ),
    ]
