# Generated by Django 5.0 on 2025-10-21 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_applicantprivacysettings_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicantprivacysettings',
            name='allow_messages',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
