# Generated by Django 5.2.6 on 2025-11-06 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_applicantprivacysettings_allow_messages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='country',
            field=models.CharField(default='USA', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='applicant',
            name='post_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='city',
            field=models.CharField(blank=True, help_text='City', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='country',
            field=models.CharField(default='USA', help_text='Country', max_length=100),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='post_code',
            field=models.CharField(blank=True, help_text='ZIP/Postal code', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='state',
            field=models.CharField(blank=True, help_text='State', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='recruiter',
            name='street_address',
            field=models.CharField(blank=True, help_text='Street address', max_length=200, null=True),
        ),
    ]
