# Generated by Django 5.2.5 on 2025-11-12 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_applicant_city_applicant_country_applicant_post_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='location_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='applicant',
            name='location_lon',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
