# Generated by Django 5.0 on 2025-10-23 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_remove_applicantprivacysettings_allow_messages_and_more'),
        ('jobs', '0009_rename_stage_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name for this search', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('skills_search', models.CharField(blank=True, help_text='Skills to search for', max_length=500)),
                ('location_search', models.CharField(blank=True, help_text='Location preference', max_length=200)),
                ('experience_level', models.CharField(blank=True, help_text='Experience level (entry, mid, senior)', max_length=50)),
                ('education_level', models.CharField(blank=True, help_text='Education level', max_length=50)),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remote_preference', models.BooleanField(default=False, help_text='Remote work preference')),
                ('visa_sponsorship', models.BooleanField(default=False, help_text='Visa sponsorship required')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether to send notifications for this search')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_searches', to='accounts.recruiter')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CandidateNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('new_match', 'New Candidate Match'), ('candidate_applied', 'Saved Candidate Applied'), ('profile_updated', 'Saved Candidate Updated Profile'), ('job_match', 'Candidate Matches Job Posting')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.applicant')),
                ('job_posting', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='jobs.jobposting')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='accounts.recruiter')),
                ('saved_search', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='recruiter.savedsearch')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavedCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, help_text="Recruiter's notes about this candidate")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_by_recruiters', to='accounts.applicant')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saved_candidates', to='accounts.recruiter')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('recruiter', 'candidate')},
            },
        ),
    ]
