# Generated by Django 5.0 on 2025-10-23 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruiter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='savedsearch',
            name='availability',
            field=models.CharField(blank=True, help_text='Availability status', max_length=50),
        ),
    ]
